# Generated by Django 6.0.2 on 2026-03-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
