# Generated by Django 6.0.2 on 2026-03-17 00:57

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_department_description_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('leader', 'Leader'), ('member', 'Member')], default='member', max_length=50),
        ),
    ]
